apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: hello-function
  name: hello-function
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: hello-function
  sessionAffinity: None
  type: NodePort
