apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: brownfield-function-for-online-stores
  description: Brownfield Function for Online Stores
  tags:
    - onlinestore-dev
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=backend-api-for-online-stores'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
