#@ load("@ytt:data", "data") 
--- 
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: #@ data.values.artifactId
  description: Backstage GUI component config
  annotations:
    'backstage.io/kubernetes-label-selector': #@ "app.kubernetes.io/part-of:" + data.values.parentApp
spec:
  type: service
  lifecycle: development
  owner: my-team
  system: #@ data.values.parentApp
