#@ load("@ytt:data", "data") 
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.artifactId
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: #@ data.values.parentApp
spec:
  source:
    git:
      url: #@ "https://github.com/dektlong/" + data.values.artifactId
      ref:
        branch: main
