apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name
spec:
  selector:
    matchLabels:
      app: app-name
  template:
    metadata:
      labels:
        app: app-name
    spec:
      imagePullSecrets: 
      - name: imagereg-secret
      containers:
        - name: app-name
          image: app-name:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-name-service
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: app-name
