apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: app-name
  labels:
    app.tanzu.vmware.com/workload-type: web

spec:
  source:
    git:
      url: git-repo
      ref:
        branch: "dev"

  resources:
    requests:
      memory: 1Gi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 4000m
