#@ load("@ytt:data", "data") 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.artifactId
spec:
  selector:
    matchLabels:
      app: #@ data.values.artifactId
  template:
    metadata:
      labels:
        app: #@ data.values.artifactId
    spec:
      imagePullSecrets: 
      - name: imagereg-secret
      containers:
        - name: #@ data.values.artifactId
          image: #@ data.values.artifactId + ":latest"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.artifactId + "-service"
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: #@ data.values.artifactId
