#@ load("@ytt:data", "data") 
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: #@ data.values.artifactId
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: #@ data.values.artifactId + ":latest"
#@ data.values.scaleToZero 
        autoscaling.knative.dev/enable-scale-to-zero: true
#@ end
      name: test
    spec:
      containerConcurrency: 10
      containers:
      - env:
        - name: REV
          value: #@ "revision 1 of " + data.values.artifactId + " function"
        image: #@ data.values.artifactId + ":latest"
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
