#@ load("@ytt:data", "data") 
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: #@ data.values.artifactId
spec:
  template:
#@ if data.values.scaleToZero
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/enable-scale-to-zero: true
#@ end
    spec:
      containers:
      - image: #@ "dev-registry.example.com/" + data.values.artifactId + ":latest"
        env:
        - name: REV
          value: #@ "revision 1 of " + data.values.artifactId + " function"
