#@ load("@ytt:data", "data") 
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.artifactId
  labels:
    app.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: main
