#@ load("@ytt:data", "data") 
---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: #@ data.values.artifactId
  labels:
    app.kubernetes.io/name: #@ data.values.artifactId
    app.tanzu.vmware.com/workload-type: online-store
spec:
  source:
    git:
      url: #@ data.values.gitRepo
      ref:
        branch: "dev"
  env:
  - name: BROWNFIELD_API
    value: #@ data.values.sampleAPI
