apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-name
spec:
  template:
    metadata:
      annotations:
        client.knative.dev/user-image: app-name:latest
        autoscaling.knative.dev/enable-scale-to-zero: scale-to-zero-value
      name: app-name-v1
    spec:
      containerConcurrency: 10
      containers:
      - env:
        - name: TARGET
          value: revision 1 of app-name function
        image: registryPrefix/app-name:latest
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
status: {}
